blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/rdc-autonomous-mobile-robot-project/tsukuba2023_ToDo/issues/new?template=custom.md
